#!/usr/bin/env python
# -*- coding: utf-8 -*-

from typing import List

from attr import attrib, attrs


class Namelist(object):
    ...


@attrs
class ControlNamelist(Namelist):
    calculation:  str = attrib(converter=str)
    title:  str = attrib(converter=str)
    verbosity:  str = attrib(converter=str)
    restart_mode:  str = attrib(converter=str)
    wf_collect:  bool = attrib(converter=bool)
    nstep:  int = attrib(converter=int)
    iprint:  int = attrib(converter=int)
    tstress:  bool = attrib(converter=bool)
    tprnfor:  bool = attrib(converter=bool)
    dt:  float = attrib(converter=float)
    outdir:  str = attrib(converter=str)
    wfcdir:  str = attrib(converter=str)
    prefix:  str = attrib(converter=str)
    lkpoint_dir:  bool = attrib(converter=bool)
    max_seconds:  float = attrib(converter=float)
    etot_conv_thr:  float = attrib(converter=float)
    forc_conv_thr:  float = attrib(converter=float)
    disk_io:  str = attrib(converter=str)
    pseudo_dir:  str = attrib(converter=str)
    tefield:  bool = attrib(converter=bool)
    dipfield:  bool = attrib(converter=bool)
    lelfield:  bool = attrib(converter=bool)
    nberrycyc:  int = attrib(converter=int)
    lorbm:  bool = attrib(converter=bool)
    lberry:  bool = attrib(converter=bool)
    gdir:  int = attrib(converter=int)
    nppstr:  int = attrib(converter=int)
    lfcpopt:  bool = attrib(converter=bool)
    gate:  bool = attrib(converter=bool)


@attrs
class SystemNamelist(Namelist):
    ibrav:  int = attrib(converter=int)
    celldm:  List[float] = attrib(converter=List[float])
    A:  float = attrib(converter=float)
    B:  float = attrib(converter=float)
    C:  float = attrib(converter=float)
    cosAB:  float = attrib(converter=float)
    cosAC:  float = attrib(converter=float)
    cosBC:  float = attrib(converter=float)
    nat:  int = attrib(converter=int)
    ntyp:  int = attrib(converter=int)
    nbnd:  int = attrib(converter=int)
    tot_charge:  float = attrib(converter=float)
    starting_charge:  List[float] = attrib(converter=List[float])
    tot_magnetization:  float = attrib(converter=float)
    starting_magnetization:  List[float] = attrib(converter=List[float])
    ecutwfc:  float = attrib(converter=float)
    ecutrho:  float = attrib(converter=float)
    ecutfock:  float = attrib(converter=float)
    nr1:  int = attrib(converter=int)
    nr2:  int = attrib(converter=int)
    nr3:  int = attrib(converter=int)
    nr1s:  int = attrib(converter=int)
    nr2s:  int = attrib(converter=int)
    nr3s:  int = attrib(converter=int)
    nosym:  bool = attrib(converter=bool)
    nosym_evc:  bool = attrib(converter=bool)
    noinv:  bool = attrib(converter=bool)
    no_t_rev:  bool = attrib(converter=bool)
    force_symmorphic:  bool = attrib(converter=bool)
    use_all_frac:  bool = attrib(converter=bool)
    occupations:  str = attrib(converter=str)
    one_atom_occupations:  bool = attrib(converter=bool)
    starting_spin_angle:  bool = attrib(converter=bool)
    degauss:  float = attrib(converter=float)
    smearing:  str = attrib(converter=str)
    nspin:  int = attrib(converter=int)
    noncolin:  bool = attrib(converter=bool)
    ecfixed:  float = attrib(converter=float)
    qcutz:  float = attrib(converter=float)
    q2sigma:  float = attrib(converter=float)
    input_dft:  str = attrib(converter=str)
    exx_fraction:  float = attrib(converter=float)
    screening_parameter:  float = attrib(converter=float)
    exxdiv_treatment:  str = attrib(converter=str)
    x_gamma_extrapolation:  bool = attrib(converter=bool)
    ecutvcut:  float = attrib(converter=float)
    nqx1:  int = attrib(converter=int)
    nqx2:  int = attrib(converter=int)
    nqx3:  int = attrib(converter=int)
    lda_plus_u:  bool = attrib(converter=bool)
    lda_plus_u_kind:  int = attrib(converter=int)
    Hubbard_U:  List[float] = attrib(converter=List[float])
    Hubbard_J0:  List[float] = attrib(converter=List[float])
    Hubbard_alpha:  List[float] = attrib(converter=List[float])
    Hubbard_beta:  List[float] = attrib(converter=List[float])
    Hubbard_J:  List[float] = attrib(converter=List[float])
    starting_ns_eigenvalue:  float = attrib(converter=float)
    U_projection_type:  str = attrib(converter=str)
    edir:  int = attrib(converter=int)
    emaxpos:  float = attrib(converter=float)
    eopreg:  float = attrib(converter=float)
    eamp:  float = attrib(converter=float)
    angle1:  List[float] = attrib(converter=List[float])
    angle2:  List[float] = attrib(converter=List[float])
    constrained_magnetization:  str = attrib(converter=str)
    fixed_magnetization:  List[float] = attrib(converter=List[float])
    # lambda:  float = attrib(converter=float)
    report:  int = attrib(converter=int)
    lspinorb:  bool = attrib(converter=bool)
    assume_isolated:  str = attrib(converter=str)
    esm_bc:  str = attrib(converter=str)
    esm_w:  float = attrib(converter=float)
    esm_efield:  float = attrib(converter=float)
    esm_nfit:  int = attrib(converter=int)
    fcp_mu:  float = attrib(converter=float)
    vdw_corr:  str = attrib(converter=str)
    london:  bool = attrib(converter=bool)
    london_s6:  float = attrib(converter=float)
    london_c6:  List[float] = attrib(converter=List[float])
    london_rvdw:  List[float] = attrib(converter=List[float])
    london_rcut:  int = attrib(converter=int)
    ts_vdw_econv_thr:  float = attrib(converter=float)
    ts_vdw_isolated:  bool = attrib(converter=bool)
    xdm:  bool = attrib(converter=bool)
    xdm_a1:  float = attrib(converter=float)
    xdm_a2:  float = attrib(converter=float)
    space_group:  int = attrib(converter=int)
    uniqueb:  bool = attrib(converter=bool)
    origin_choice:  int = attrib(converter=int)
    rhombohedral:  bool = attrib(converter=bool)
    zgate:  float = attrib(converter=float)
    relaxz:  bool = attrib(converter=bool)
    block:  bool = attrib(converter=bool)
    block_1:  float = attrib(converter=float)
    block_2:  float = attrib(converter=float)
    block_height:  float = attrib(converter=float)


@attrs
class ElectronsNamelist(Namelist):
    electron_maxstep:  int = attrib(converter=int)
    scf_must_converge:  bool = attrib(converter=bool)
    conv_thr:  float = attrib(converter=float)
    adaptive_thr:  bool = attrib(converter=bool)
    conv_thr_init:  float = attrib(converter=float)
    conv_thr_multi:  float = attrib(converter=float)
    mixing_mode:  str = attrib(converter=str)
    mixing_beta:  float = attrib(converter=float)
    mixing_ndim:  int = attrib(converter=int)
    mixing_fixed_ns:  int = attrib(converter=int)
    diagonalization:  str = attrib(converter=str)
    ortho_para:  int = attrib(converter=int)
    diago_thr_init:  float = attrib(converter=float)
    diago_cg_maxiter:  int = attrib(converter=int)
    diago_david_ndim:  int = attrib(converter=int)
    diago_full_acc:  bool = attrib(converter=bool)
    efield:  float = attrib(converter=float)
    efield_cart:  tuple = attrib(converter=tuple)
    efield_phase:  str = attrib(converter=str)
    startingpot:  str = attrib(converter=str)
    startingwfc:  str = attrib(converter=str)
    tqr:  bool = attrib(converter=bool)


@attrs
class IonsNamelist(Namelist):
    ion_dynamics:  str = attrib(converter=str)
    ion_positions:  str = attrib(converter=str)
    pot_extrapolation:  str = attrib(converter=str)
    wfc_extrapolation:  str = attrib(converter=str)
    remove_rigid_rot:  bool = attrib(converter=bool)
    ion_temperature:  str = attrib(converter=str)
    tempw:  float = attrib(converter=float)
    tolp:  float = attrib(converter=float)
    delta_t:  float = attrib(converter=float)
    nraise:  int = attrib(converter=int)
    refold_pos:  bool = attrib(converter=bool)
    upscale:  float = attrib(converter=float)
    bfgs_ndim:  int = attrib(converter=int)
    trust_radius_max:  float = attrib(converter=float)
    trust_radius_min:  float = attrib(converter=float)
    trust_radius_ini:  float = attrib(converter=float)
    w_1:  float = attrib(converter=float)
    w_2:  float = attrib(converter=float)


@attrs
class CELL_NAMELIST(Namelist):
    cell_dynamics:  str = attrib(converter=str)
    press:  float = attrib(converter=float)
    wmass:  float = attrib(converter=float)
    cell_factor:  float = attrib(converter=float)
    press_conv_thr:  float = attrib(converter=float)
    cell_dofree:  str = attrib(converter=str)
